# Pytorch
Learning how to use it

In [1]:
!nvidia-smi

Thu Mar  7 09:41:01 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:01:00.0  On |                  N/A |
|  0%   35C    P8              9W /  285W |     385MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch

## Intro to Tensors
Learning different types and dimensions

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [6]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [7]:
scaler.ndim

0

In [13]:
scaler.item()

7

In [18]:
# vector
vector = torch.tensor([3, 6])
vector

tensor([3, 6])

In [19]:
vector.ndim

1

In [20]:
vector.shape

torch.Size([2])

In [21]:
# MATRIX
MATRIX = torch.tensor([[1, 4],[8, 3]])
MATRIX

tensor([[1, 4],
        [8, 3]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
# TENSOR - Basically a larger MATRIX, it is all these data types
TENSOR = torch.tensor([[1, 2, 3], [7, 3, 5], [3, 7, 4]])
TENSOR

tensor([[1, 2, 3],
        [7, 3, 5],
        [3, 7, 4]])

In [26]:
TENSOR.ndim

2

In [27]:
TENSOR.shape

torch.Size([3, 3])