# 00. PyTorch Fundamentals
Learning how to use it

In [1]:
!nvidia-smi

Thu Mar  7 10:26:09 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:01:00.0  On |                  N/A |
|  0%   34C    P8              8W /  285W |     381MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.0+cu121


## Intro to Tensors
Learning different types and dimensions

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
# vector
vector = torch.tensor([3, 6])
vector

tensor([3, 6])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[1, 4],
                       [8, 3]])
MATRIX

tensor([[1, 4],
        [8, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([1, 4])

In [13]:
# TENSOR - Basically a larger MATRIX, it is all these data types
TENSOR = torch.tensor([[[1, 2, 3], 
                        [7, 3, 5], 
                        [3, 7, 4]]
                        ])
TENSOR

tensor([[[1, 2, 3],
         [7, 3, 5],
         [3, 7, 4]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [7, 3, 5],
        [3, 7, 4]])