# 00. PyTorch Fundamentals
Learning how to use it

In [1]:
!nvidia-smi

Thu Mar  7 15:44:43 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:01:00.0  On |                  N/A |
| 53%   65C    P2            265W /  285W |    8694MiB /  16376MiB |     97%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.0+cu121


## Intro to Tensors
Learning different types and dimensions

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
# vector
vector = torch.tensor([3, 6])
vector

tensor([3, 6])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[1, 4],
                       [8, 3]])
MATRIX

tensor([[1, 4],
        [8, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([1, 4])

In [13]:
# TENSOR - Basically a larger MATRIX, it is all these data types
TENSOR = torch.tensor([[[1, 2, 3], 
                        [7, 3, 5], 
                        [3, 7, 4]]
                        ])
TENSOR

tensor([[[1, 2, 3],
         [7, 3, 5],
         [3, 7, 4]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [7, 3, 5],
        [3, 7, 4]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [24]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4) # very simple with lots of functionality
random_tensor

tensor([[0.8284, 0.8328, 0.2165, 0.6864],
        [0.0939, 0.0465, 0.9547, 0.1400],
        [0.4662, 0.1132, 0.9703, 0.7937]])

In [28]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels as in RGB, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
ones.dtype

torch.float32

In [ ]:
random_tensor